FROM node:22-alpine AS build
WORKDIR /app
COPY huellitas-frontend/package*.json ./
RUN npm ci
COPY huellitas-frontend/. .
RUN npm run build

FROM nginx:1.27-alpine
COPY huellitas-frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/huellitas-frontend/browser /usr/share/nginx/html
EXPOSE 80
