spring.application.name=HuellitasFelices

# SUPABASE (CONNECTION POOLER)
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres}
spring.datasource.username=${DB_USERNAME:postgres.cvkniojcstauhcqnkdlf}
spring.datasource.password=${DB_PASSWORD:Cristancho123}
spring.datasource.driver-class-name=org.postgresql.Driver

# HIKARI (CRITICO PARA SUPABASE)
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.keepalive-time=0

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# DEVTOOLS (DESACTIVAR)
spring.devtools.restart.enabled=false

# JWT
jwt.secret=${JWT_SECRET:VXdhV3Rhc0ZlbGljZXNBZG1pbkFjY2Vzb1RvdGFsU2VjcmV0S2V5MjAyNg==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}