create table if not exists public.auditoria_clinica (
  id_auditoria bigint generated by default as identity primary key,
  entidad varchar(80) not null,
  id_entidad bigint,
  accion varchar(40) not null,
  id_usuario bigint,
  rol_usuario varchar(40),
  resumen text,
  creado_en timestamp without time zone not null default current_timestamp,
  constraint fk_auditoria_usuario foreign key (id_usuario) references public.usuarios(id_usuario)
);

create index if not exists idx_auditoria_clinica_creado_en
  on public.auditoria_clinica (creado_en desc);

create index if not exists idx_auditoria_clinica_entidad
  on public.auditoria_clinica (entidad, id_entidad);
