create table if not exists public.clinicas (
  id_clinica bigint generated by default as identity primary key,
  nombre varchar(160) not null,
  nif varchar(40),
  telefono varchar(40),
  email varchar(160),
  direccion text,
  activa boolean not null default true,
  creado_en timestamp without time zone not null default current_timestamp
);

insert into public.clinicas (nombre, nif, telefono, email, direccion)
select 'Huellitas Felices', null, null, null, null
where not exists (select 1 from public.clinicas);

create table if not exists public.facturas (
  id_factura bigint generated by default as identity primary key,
  id_cliente bigint not null references public.clientes(id_cliente),
  id_cita bigint references public.citas(id_cita),
  numero varchar(60) unique,
  fecha date not null default current_date,
  estado varchar(30) not null default 'borrador'
    check (estado in ('borrador', 'emitida', 'pagada', 'cancelada')),
  base_imponible numeric(10, 2) not null default 0,
  impuestos numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,
  notas text,
  creado_en timestamp without time zone not null default current_timestamp
);

create table if not exists public.factura_lineas (
  id_linea bigint generated by default as identity primary key,
  id_factura bigint not null references public.facturas(id_factura) on delete cascade,
  concepto varchar(220) not null,
  cantidad numeric(10, 2) not null default 1,
  precio_unitario numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0
);

create index if not exists idx_facturas_cliente_fecha
  on public.facturas(id_cliente, fecha desc);

alter table public.clientes
  add column if not exists nif varchar(40);

alter table public.facturas
  add column if not exists impuesto_porcentaje numeric(5, 2) not null default 21,
  add column if not exists descuento_porcentaje numeric(5, 2) not null default 0,
  add column if not exists descuento numeric(10, 2) not null default 0,
  add column if not exists pago_estado varchar(30) not null default 'pendiente',
  add column if not exists pago_proveedor varchar(60),
  add column if not exists pago_referencia varchar(160);

alter table public.facturas
drop constraint if exists facturas_pago_estado_check;

alter table public.facturas
add constraint facturas_pago_estado_check
check (pago_estado in ('pendiente', 'pagado', 'cancelado', 'fallido'));

create table if not exists public.facturacion_config (
  id_config bigint generated by default as identity primary key,
  serie varchar(20) not null default 'FAC',
  impuesto_porcentaje numeric(5, 2) not null default 21,
  moneda varchar(3) not null default 'EUR',
  pago_online_activo boolean not null default false,
  proveedor_pago varchar(60),
  actualizado_en timestamp without time zone not null default current_timestamp
);

insert into public.facturacion_config (serie, impuesto_porcentaje, moneda, pago_online_activo, proveedor_pago)
select 'FAC', 21, 'EUR', false, null
where not exists (select 1 from public.facturacion_config);
