package com.veterinaria.demo.security;

public enum ClinicPermission {
    MANAGE_USERS,
    MANAGE_CLIENTS,
    MANAGE_PETS,
    MANAGE_APPOINTMENTS,
    CHANGE_APPOINTMENT_STATUS,
    MANAGE_CONSULTATIONS,
    MANAGE_TREATMENTS,
    MANAGE_DOCUMENTS,
    MANAGE_PREVENTIVES,
    MANAGE_AVAILABILITY,
    VIEW_AUDIT,
    MANAGE_INVOICES,
    VIEW_DASHBOARD
}
